#!/bin/sh
# Set volume if passed as command-line argument

if [ "$1" = listen ]
then
	while true
	do
		# Get pulseaudio volume
		volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep "/[^-]*%" | cut -d "/" -f2 | sed 's/%//')
		if [ "$volume" -ne $(eww get volume) ]
		then
			# Echo volume
			echo $volume
		fi
	done
elif [ $1 ]
then
	pactl set-sink-volume @DEFAULT_SINK@ $1%
fi

function toggle_mute() {
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	if [ $(eww get vol_icon) = "ﱝ" ]
	then
		eww update vol_icon="墳"
	else
		eww update vol_icon="ﱝ"
	fi
}

